// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAalQyWvA2BKwSBR98G0ZDeV8OwwZfFHXI',
    appId: '1:1006735223733:web:659f93a7b2c68a2c85c7fc',
    messagingSenderId: '1006735223733',
    projectId: 'siksiklabuyo-d9974',
    authDomain: 'siksiklabuyo-d9974.firebaseapp.com',
    storageBucket: 'siksiklabuyo-d9974.appspot.com',
    measurementId: 'G-LGLHEB436J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_YUDse0SHY3N5fizUQVU9PcbQUYsZuA',
    appId: '1:1006735223733:android:b49d39df3a643f5b85c7fc',
    messagingSenderId: '1006735223733',
    projectId: 'siksiklabuyo-d9974',
    storageBucket: 'siksiklabuyo-d9974.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo0THRrwQYbsaLX3lckQYbZ1Umd2tspJ4',
    appId: '1:1006735223733:ios:7e61d055b9a9ee9b85c7fc',
    messagingSenderId: '1006735223733',
    projectId: 'siksiklabuyo-d9974',
    storageBucket: 'siksiklabuyo-d9974.appspot.com',
    iosClientId: '1006735223733-45ne6rc9ufdjfhue4crteprq8bjhlf83.apps.googleusercontent.com',
    iosBundleId: 'com.example.siksikLabuyo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo0THRrwQYbsaLX3lckQYbZ1Umd2tspJ4',
    appId: '1:1006735223733:ios:7e61d055b9a9ee9b85c7fc',
    messagingSenderId: '1006735223733',
    projectId: 'siksiklabuyo-d9974',
    storageBucket: 'siksiklabuyo-d9974.appspot.com',
    iosClientId: '1006735223733-45ne6rc9ufdjfhue4crteprq8bjhlf83.apps.googleusercontent.com',
    iosBundleId: 'com.example.siksikLabuyo',
  );
}
